config/routes.rb
Rails.application.routes.draw do
	root "users#index"
	resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
	validates :name, presence:true
	validates :email, presence:true, uniqueness: {case_insensitive:false}

	has_secure_password
	validates :email, email_format: { message: "Wrong email format" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.all
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new user_params
		if @user.save
			redirect_to root_path, notice: "Account created"
		else
			render 'new'
		end
	end

	private

	def user_params
		params.require(:user).permit(:name, :email, :password)
	end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Cchat</title>
	<%= csrf_meta_tags %>

	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

	<nav class="navbar navbar-dark bg-primary">
		<a class="navbar-brand" href="/">CCHAT</a>
		<ul class="nav navbar-nav">
			<li class="nav-item active">
				<a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
			</li>
			<li class="nav-item">
				
			</li>
		</ul>
		<form class="form-inline pull-xs-right">
			<%= link_to "Create An Account", new_user_path, class: "btn btn-success" %>
		</form>
	</nav>

	<div class="container">
	<div class="row">
		<%= yield %>
		</div>
	</div>
</body>
</html>

app/views/users/index.html.erb
<div class="row">
<h1>Users</h1>
	<div class="container">
	<table class="table table-bordered">
			<thead class="bg-primary">
				<tr>

					<th>Name</th>
					<th>Email</th>
					<th>Create at</th>
				</tr>
			</thead>
			<tbody>
				<% @users.each do |user| %>
				<tr>
					<td><%=user.name%></td>
					<td><%=user.email%></td>
					<td><%= time_ago_in_words user.created_at %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>

app/views/users/new.html.erb
<div class="row">
	<div class="container">
		<h1>Create an Account</h1>


		<%= form_for @user do |f| %>
		
		<% unless @user.errors.empty? %>
		<div class="alert alert-danger">
			<ul>
				<% @user.errors.full_messages.each do |message| %>

				<li>
					<%= message %>
				</li>

				<%end%>
			</ul>
		</div>

		<%end%>
		
		<div class="form-group">
			<%= f.label :name %>
			<%= f.text_field :name, placeholder:"Enter your name.....", class: "form-control" %>
			
		</div>

		<div class="form-group">
			<%= f.label :email %>
			<%= f.text_field :email, placeholder:"Enter your email.....", class: "form-control" %>
		</div>

		<div class="form-group">
			<%= f.label :password %>
			<%= f.password_field :password, placeholder:"Enter your password.....", class: "form-control" %>
		</div>


		<%=f.submit "Create Account", class:"btn btn-primary" %>
		<% end %>
	</div>
</div>

<form action="/users" method="post">
	
</form>